# FROM nginx:1.27-alpine
# RUN apk add openssl

FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
build-essential \
curl \
wget \
libpcre3 \
libpcre3-dev \
zlib1g \
zlib1g-dev \
libssl-dev

ARG NginxVersion=nginx-1.9.0

COPY ${NginxVersion}.tar.gz /${NginxVersion}.tar.gz

RUN tar -zxvf ${NginxVersion}.tar.gz

ARG OpensslName=openssl-1.0.1u
COPY ${OpensslName}.tar.gz /${OpensslName}.tar.gz

RUN tar -zxvf /${OpensslName}.tar.gz

WORKDIR /${NginxVersion}

RUN ./configure --with-http_ssl_module --with-openssl=/${OpensslName} --with-openssl-opt='enable-weak-ssl-ciphers enable-rc4 enable-ssl2 enable-des' --with-http_gzip_static_module --with-cc-opt="-Wno-error"
RUN make
RUN make install

# RUN openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 \
#     -subj "/C=CN/ST=Italy/O=Example Company/CN=example.com" \
#     -keyout /usr/local/nginx/conf/server.key -out /usr/local/nginx/conf/server.crt
#
# RUN openssl ecparam -name prime256v1 -genkey -noout -out key.pem
#
# RUN openssl req -new -key key.pem -days 3650 -nodes -x509 \
#     -subj "/C=CN/ST=Italy/O=Example Company/CN=example.com" \
#     -keyout /usr/local/nginx/conf/server_ec.key -out /usr/local/nginx/conf/server_ec.crt

# WORKDIR /etc/nginx
# RUN openssl req -x509 -nodes -newkey rsa:2048 \
# -keyout server.key -out server.crt \
# -days 7 \
# -subj "/C=SZ/ST=Hhohho/L=Mbabane/O=The Organization of African Christians/OU=FaithLab/CN=Uvuvwevwevwe@eswatini.christ"

RUN mkdir /etc/nginx

RUN openssl genrsa -out /etc/nginx/server.key 512
RUN openssl req -new -x509 -key /etc/nginx/server.key -out /etc/nginx/server.crt -days 365 \
-subj "/C=XX/ST=Lab/L=Lab/O=Example/OU=Lab/CN=localhost"

RUN chmod 600 /etc/nginx/server.key

RUN openssl dhparam -out /etc/nginx/dhparam.pem 512

COPY nginx.conf /etc/nginx/nginx.conf

COPY openssl.cnf /etc/ssl/openssl.cnf
ENV OPENSSL_CONF=/etc/ssl/openssl.cnf

# COPY nginx.conf /usr/local/nginx/conf/nginx.conf

RUN /usr/local/nginx/sbin/nginx -t

CMD ["/usr/local/nginx/sbin/nginx", "-g", "daemon off;"]

# COPY server.crt /etc/nginx/server.crt
# COPY server.key /etc/nginx/server.key
# COPY dhparam.pem /etc/nginx/dhparam.pem
